version: "3.9"
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      PGDATA: "%USERPPROFILE%\postgresdb"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G